### ISSUE TITLE
Error when trying to connect to Ocean

### ISSUE THREAD

**Issue by santteegt** [oceanprotocol/squid-js#103]
## Expected Behavior

When trying to get an OceanInstance using `Ocean.getInstance(config)`, I'm getting the following error:

```
Failed to load OceanMarket from spree { Error: Cannot find module '@oceanprotocol/keeper-contracts/artifacts/OceanMarket.spree.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Function.<anonymous> (/Users/santteegt/GitRepositories/clones/faucet/server/node_modules/@oceanprotocol/squid/src/keeper/ContractHandler.ts:34:26)
    at step (/Users/santteegt/GitRepositories/clones/faucet/server/node_modules/@oceanprotocol/squid/dist/node/keeper/ContractHandler.js:32:23)
    at Object.next (/Users/santteegt/GitRepositories/clones/faucet/server/node_modules/@oceanprotocol/squid/dist/node/keeper/ContractHandler.js:13:53)
    at /Users/santteegt/GitRepositories/clones/faucet/server/node_modules/@oceanprotocol/squid/dist/node/keeper/ContractHandler.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/santteegt/GitRepositories/clones/faucet/server/node_modules/@oceanprotocol/squid/dist/node/keeper/ContractHandler.js:3:12)
    at Function.ContractHandler.load (/Users/santteegt/GitRepositories/clones/faucet/server/node_modules/@oceanprotocol/squid/dist/node/keeper/ContractHandler.js:81:16)
    at Function.<anonymous> (/Users/santteegt/GitRepositories/clones/faucet/server/node_modules/@oceanprotocol/squid/src/keeper/ContractHandler.ts:12:81)
    at step (/Users/santteegt/GitRepositories/clones/faucet/server/node_modules/@oceanprotocol/squid/dist/node/keeper/ContractHandler.js:32:23)
    at Object.next (/Users/santteegt/GitRepositories/clones/faucet/server/node_modules/@oceanprotocol/squid/dist/node/keeper/ContractHandler.js:13:53)
    at fulfilled (/Users/santteegt/GitRepositories/clones/faucet/server/node_modules/@oceanprotocol/squid/dist/node/keeper/ContractHandler.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) code: 'MODULE_NOT_FOUND' }
```
I'm running a local spree tesnet using latest changes on [https://github.com/oceanprotocol/barge](barge) however previous versions of the testnet allowed me to connect without any errors

## Current Behavior

My app immediately crashes when trying to get an Ocean connection instance using latest version of squid-js. I'm running a local spree testnet using docker, and Ocean contracts ABI (`*.spree.json`) were properly being located in `~/.ocean/keeper-contracts/artifacts/`

## Step to Reproduce the problem

1. Deploy a dockerized Spree testnet using latest version of barge, and make sure it is up and running

```
$./start_ocean.sh --latest --local-spree-node --force-pull
```

2. Create a (ES6-enabled) server application using NodeJS v8.11.3
4. Add squid-js node package `npm install @oceanprotocol/squid`
4. Create a server.js file:

```
import { Ocean } from '@oceanprotocol/squid';
Ocean.getInstance(config.oceanConfig).then((ocean) => {
    console.log('success')
    console.log(ocean)
}).catch((error) => {
  logger.error(`Error when trying to connect to Ocean Protocol: ${error}`)
  process.exit(1);
});
```

5. Run serve app (e.g. using nodemon)

## Specifications

* Version: 0.2.6
* JavaScript: ES6
* Node: 8.11.3
* OS: macOS
* Docker: 18.09.0, build 4d60db4

**Comment by H34D** [comment]
### Problem

The `spree` network is not persistent (because it only lives inside your docker instance). Therefore we cannot release artefacts for it in the `keeper-contracts` npm package (because the addresses are different all the time). This means `squid-js` cannot get them from npm. 

The `*.spree.json` artefacts are only used inside docker and are shared among the different docker containers and should not be shared with the outside world.

### Workaround

1. Run `barge` with `--local-nile-node` or `--local-kovan-node` to connect to a persistent Blockchain and use the `kovan` or `nile` artefacts.
2. Do the following:
```bash
git clone git@github.com:oceanprotocol/keeper-contracts.git
cd keeper-contracts
npm i
npm migrate:spree
```
This will create the `spree` artefacts locally. Now you need to expose them and use them:
```bash
cd keeper-contracts
npm link
cd ../squid-js
npm link @oceanprotocol/keeper-contracts
```
This will link the npm package `keeper-contracts` (containing the `*.spree.json` artefacts)
3. Super hacky (don't do it):
```bash
cd squid-js
cp ~/.ocean/keeper-contracts/artifacts/*.spree.json ./node_modules/@oceanprotocol/keeper-contracts/artifacts/
```
